# Generated by Django 2.2.4 on 2019-12-16 07:15

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('individual_share_b', otree.db.models.CurrencyField(null=True, verbose_name='How much would you like to offer player B?')),
                ('offer_accept', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Do you accept this offer?')),
                ('individual_share_a', otree.db.models.CurrencyField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appsvoug_group', to='otree.Session')),
            ],
            options={
                'db_table': 'AppSVOUG_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appsvoug_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'AppSVOUG_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('response_0', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 0 points?')),
                ('response_10', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 10 points?')),
                ('response_20', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Would you accept an offer of 20 points?')),
                ('response_30', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Would you accept an offer of 30 points?')),
                ('response_40', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 40 points?')),
                ('response_50', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Would you accept an offer of 50 points?')),
                ('response_60', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 60 points?')),
                ('response_70', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 70 points?')),
                ('response_80', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 80 points?')),
                ('response_90', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 90 points?')),
                ('response_100', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Would you accept an offer of 100 points?')),
                ('offer_amount', otree.db.models.CurrencyField(null=True, verbose_name='How much would you like to offer player B?')),
                ('accept_offer', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Do you accept this offer?')),
                ('s', otree.db.models.CurrencyField(null=True)),
                ('slider1', otree.db.models.FloatField(null=True)),
                ('slider2', otree.db.models.FloatField(null=True)),
                ('slider3', otree.db.models.FloatField(null=True)),
                ('slider4', otree.db.models.FloatField(null=True)),
                ('slider5', otree.db.models.FloatField(null=True)),
                ('slider6', otree.db.models.FloatField(null=True)),
                ('slider_angle', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('slider_classification', otree.db.models.StringField(max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSVOUG.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appsvoug_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appsvoug_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSVOUG.Subsession')),
            ],
            options={
                'db_table': 'AppSVOUG_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSVOUG.Subsession'),
        ),
    ]
