# Generated by Django 2.2.4 on 2019-12-16 08:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='individual_share_b',
            field=otree.db.models.CurrencyField(null=True, verbose_name='你愿意分配多少点数给玩家B?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='offer_accept',
            field=otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='你是否接受这个方案?'),
        ),
    ]
