# Generated by Django 2.2.4 on 2019-12-16 08:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0002_auto_20191216_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='accept_offer',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='Do you accept this offer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_0',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你0点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_10',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你10点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_100',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你100点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_20',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='你是否接受分配给你20点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_30',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='你是否接受分配给你30点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_40',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你40点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_50',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='你是否接受分配给你50点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_60',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你60点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_70',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你70点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_80',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你80点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_90',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你90点数的分配？'),
        ),
    ]
