# Generated by Django 2.2.4 on 2019-12-16 08:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0003_auto_20191216_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='response_20',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你20点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_30',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你30点数的分配？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='response_50',
            field=otree.db.models.BooleanField(choices=[[True, '是'], [False, '否']], null=True, verbose_name='你是否接受分配给你50点数的分配？'),
        ),
    ]
