# Generated by Django 2.2.4 on 2019-12-16 08:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0004_auto_20191216_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='offer_accept',
            field=otree.db.models.BooleanField(choices=[[True, '接受'], [False, '不接受']], null=True, verbose_name='你是否接受这个方案?'),
        ),
    ]
