# Generated by Django 2.2.4 on 2019-12-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0006_auto_20191216_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='individual_share_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='offer_amount',
        ),
    ]
