# Generated by Django 2.2.4 on 2019-12-20 06:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0007_auto_20191216_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='individual_share_a',
        ),
        migrations.RemoveField(
            model_name='group',
            name='offer_accept',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_0',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_100',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_20',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_30',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_40',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_50',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_60',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_70',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_80',
        ),
        migrations.RemoveField(
            model_name='player',
            name='response_90',
        ),
        migrations.AddField(
            model_name='player',
            name='fake_svo_angle',
            field=otree.db.models.FloatField(default=35.57, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fake_svo_classificaiton',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='individual_share_a',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='offer_accept',
            field=otree.db.models.BooleanField(choices=[[True, '接受'], [False, '不接受']], null=True, verbose_name='你是否接受这个方案?'),
        ),
    ]
