# Generated by Django 2.2.4 on 2019-12-20 07:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0026_auto_20191220_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fake_svo_angle',
            field=otree.db.models.FloatField(default=-1.58, null=True),
        ),
    ]
