# Generated by Django 2.2.4 on 2019-12-20 08:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0031_auto_20191220_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fake_svo_classificaiton',
        ),
        migrations.AlterField(
            model_name='player',
            name='fake_svo_angle',
            field=otree.db.models.FloatField(default=-5.85, null=True),
        ),
    ]
