# Generated by Django 2.2.4 on 2019-12-20 09:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0037_auto_20191220_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='individual_share_a',
        ),
        migrations.AlterField(
            model_name='player',
            name='fake_svo_angle',
            field=otree.db.models.FloatField(default=-10.16, null=True),
        ),
    ]
