# Generated by Django 2.2.4 on 2019-12-20 09:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0040_auto_20191220_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='individual_share_a',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fake_svo_angle',
            field=otree.db.models.FloatField(default=20.95, null=True),
        ),
    ]
