# Generated by Django 2.2.4 on 2019-12-20 10:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0042_auto_20191220_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fake_svo_angle',
        ),
        migrations.AddField(
            model_name='player',
            name='individual_share_a',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
