# Generated by Django 2.2.4 on 2019-12-20 12:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0043_auto_20191220_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bfeeling_rating',
            field=otree.db.models.BooleanField(choices=[[True, '接受'], [False, '不接受']], null=True, verbose_name='你是否接受这个方案?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gfeeling_rating',
            field=otree.db.models.BooleanField(choices=[[True, '接受'], [False, '不接受']], null=True, verbose_name='你是否接受这个方案?'),
        ),
    ]
