# Generated by Django 2.2.4 on 2019-12-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0046_auto_20191220_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bfeeling_rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gfeeling_rating',
        ),
    ]
