# Generated by Django 2.2.4 on 2019-12-20 14:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0047_auto_20191220_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='feeling_rating',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
