# Generated by Django 2.2.4 on 2019-12-21 07:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0048_player_feeling_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='offer_accept',
        ),
        migrations.AddField(
            model_name='player',
            name='shared_point',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
