# Generated by Django 2.2.4 on 2019-12-21 09:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0051_remove_player_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fake_svo_angle',
            field=otree.db.models.DecimalField(null=True),
        ),
    ]
