# Generated by Django 2.2.4 on 2019-12-21 09:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0053_auto_20191221_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shared_point',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
