# Generated by Django 2.2.4 on 2019-12-21 13:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0054_auto_20191221_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='individual_share_a',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
