# Generated by Django 2.2.4 on 2019-12-21 13:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0055_auto_20191221_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='individual_share_a',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='shared_point',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
