# Generated by Django 2.2.4 on 2019-12-22 05:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0056_auto_20191221_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='fake_svo_angle',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='individual_share_a',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='shared_point',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='slider_angle',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='slider_classification',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
