# Generated by Django 2.2.4 on 2019-12-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0062_auto_20191222_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='shared_point',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slider_angle',
        ),
    ]
