# Generated by Django 2.2.4 on 2019-12-22 08:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0065_player_slider_angle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shared_point',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
