# Generated by Django 2.2.4 on 2019-12-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0068_auto_20191223_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fake_svo_angle',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shared_point',
        ),
    ]
