# Generated by Django 2.2.4 on 2019-12-23 09:04

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0074_auto_20191223_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='slider_angle',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
