# Generated by Django 2.2.4 on 2019-12-23 09:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0075_auto_20191223_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='feeling_rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shared_point',
        ),
        migrations.AddField(
            model_name='player',
            name='accept_offer',
            field=otree.db.models.BooleanField(choices=[[True, '接受'], [False, '不接受']], null=True, verbose_name='你是否接受这个方案?'),
        ),
        migrations.AddField(
            model_name='player',
            name='fake_svo_classificaiton',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slider_angle',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
