# Generated by Django 2.2.4 on 2019-12-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0078_remove_player_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='fsvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AppSVOUG_fsvo',
            },
        ),
    ]
