# Generated by Django 2.2.4 on 2019-12-24 03:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0080_auto_20191224_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='offer_accept',
            field=otree.db.models.BooleanField(choices=[[True, '接受'], [False, '不接受']], null=True, verbose_name='你是否接受这个方案?'),
        ),
    ]
