# Generated by Django 2.2.4 on 2019-12-24 06:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0081_auto_20191224_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='feeling_ratings',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
