# Generated by Django 2.2.4 on 2019-12-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0082_player_feeling_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='shared_point',
        ),
    ]
