# Generated by Django 2.2.4 on 2019-12-24 08:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0083_remove_player_shared_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shared_point',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
