# Generated by Django 2.2.4 on 2019-12-24 11:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0084_player_shared_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='feeling_ratings',
        ),
        migrations.AddField(
            model_name='player',
            name='feeling_rating',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
