# Generated by Django 2.2.4 on 2019-12-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0085_auto_20191224_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='feeling_rating',
        ),
    ]
