# Generated by Django 2.2.4 on 2019-12-24 12:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0086_remove_player_feeling_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='feeling_rating',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
