# Generated by Django 2.2.4 on 2019-12-25 08:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0087_player_feeling_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fake_svo_angle',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
