# Generated by Django 2.2.4 on 2019-12-25 10:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0089_auto_20191225_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fake_svo_classificaiton',
        ),
        migrations.AddField(
            model_name='player',
            name='fake_svo_classification',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
