# Generated by Django 2.2.4 on 2019-12-26 06:58

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0092_auto_20191226_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='individual_share_a',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
