# Generated by Django 2.2.4 on 2019-12-27 02:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0094_auto_20191227_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=otree.db.models.IntegerField(null=True, verbose_name='请输入您的年龄：'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[[1, '男'], [2, '女']], max_length=10000, null=True, verbose_name='请输入您的性别：'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='请输入您的姓名：'),
        ),
    ]
