# Generated by Django 2.2.4 on 2019-12-27 06:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0096_auto_20191227_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='career',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='请输入您的职业'),
        ),
        migrations.AddField(
            model_name='player',
            name='contact',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='请输入您的联系方式（支付宝绑定的手机号）'),
        ),
        migrations.AddField(
            model_name='player',
            name='institute',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='请输入您的工作单位'),
        ),
        migrations.AddField(
            model_name='player',
            name='otherinfo',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='如有被试费用相关信息请在此处，请在此处说明'),
        ),
        migrations.AddField(
            model_name='player',
            name='subjectid',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='请输入您的身份证号（用于报销凭证）'),
        ),
    ]
