# Generated by Django 2.2.4 on 2019-12-27 06:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0097_auto_20191227_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='institute',
        ),
        migrations.AddField(
            model_name='player',
            name='education',
            field=otree.db.models.StringField(blank=True, choices=[('小学', '小学'), ('中学', '中学'), ('高中', '高中'), ('大学', '大学'), ('高于 ed. 1y', '高于 ed. 1y'), ('高于 ed. 2y', '高于 ed. 2y'), ('高于 ed. 3y', '高于 ed. 3y'), ('高于 ed. 4y', '高于 ed. 4y'), ('高于 ed. 5y', '高于 ed. 5y'), ('高于 ed. 6y', '高于 ed. 6y'), ('高于 ed. 7y', '高于 ed. 7y'), ('高于 ed. 8y', '高于 ed. 8y'), ('高于 ed. 9y', '高于 ed. 9y'), ('教育年限超过 10年', '教育年限超过 10年')], max_length=10000, null=True, verbose_name='请输入您的受教育程度'),
        ),
    ]
