# Generated by Django 2.2.4 on 2019-12-27 06:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0098_auto_20191227_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='education',
            field=otree.db.models.StringField(blank=True, choices=[('小学', '小学'), ('中学', '中学'), ('高中', '高中'), ('大学', '大学'), ('大学毕业后 1y 年', '大学毕业后 1y 年'), ('大学毕业后 2y 年', '大学毕业后 2y 年'), ('大学毕业后 3y 年', '大学毕业后 3y 年'), ('大学毕业后 4y 年', '大学毕业后 4y 年'), ('大学毕业后 5y 年', '大学毕业后 5y 年'), ('大学毕业后 6y 年', '大学毕业后 6y 年'), ('大学毕业后 7y 年', '大学毕业后 7y 年'), ('大学毕业后 8y 年', '大学毕业后 8y 年'), ('大学毕业后 9y 年', '大学毕业后 9y 年'), ('教育年限超过 10年', '教育年限超过 10年')], max_length=10000, null=True, verbose_name='请输入您的受教育程度'),
        ),
    ]
