# Generated by Django 2.2.4 on 2019-12-27 06:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0100_auto_20191227_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='education',
            field=otree.db.models.StringField(blank=True, choices=[('小学', '小学'), ('中学', '中学'), ('高中', '高中'), ('大学', '大学'), ('大学毕业后 1 年', '大学毕业后 1 年'), ('大学毕业后 2 年', '大学毕业后 2 年'), ('大学毕业后 3 年', '大学毕业后 3 年'), ('大学毕业后 4 年', '大学毕业后 4 年'), ('大学毕业后 5 年', '大学毕业后 5 年'), ('大学毕业后 6 年', '大学毕业后 6 年'), ('大学毕业后 7 年', '大学毕业后 7 年'), ('大学毕业后 8 年', '大学毕业后 8 年'), ('大学毕业后 9 年', '大学毕业后 9 年'), ('大学毕业后超过 10年', '大学毕业后超过 10年')], max_length=10000, null=True, verbose_name='请输入您的受教育程度'),
        ),
    ]
