# Generated by Django 2.2.4 on 2019-12-27 06:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0102_auto_20191227_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='education',
            field=otree.db.models.StringField(blank=True, choices=[('小学', '小学'), ('中学', '中学'), ('高中', '高中'), ('大学', '大学'), ('大学后进阶教育 1 年', '大学后进阶教育 1 年'), ('大学后进阶教育 2 年', '大学后进阶教育 2 年'), ('大学后进阶教育 3 年', '大学后进阶教育 3 年'), ('大学后进阶教育 4 年', '大学后进阶教育 4 年'), ('大学后进阶教育 5 年', '大学后进阶教育 5 年'), ('大学后进阶教育 6 年', '大学后进阶教育 6 年'), ('大学后进阶教育 7 年', '大学后进阶教育 7 年'), ('大学后进阶教育 8 年', '大学后进阶教育 8 年'), ('大学后进阶教育 9 年', '大学后进阶教育 9 年'), ('持续进阶教育达到 10年及以上', '持续进阶教育达到 10年及以上')], max_length=10000, null=True, verbose_name='请输入您的受教育程度'),
        ),
    ]
