# Generated by Django 2.2.4 on 2019-12-27 08:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSVOUG', '0103_auto_20191227_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.IntegerField(choices=[[1, '男'], [2, '女']], null=True, verbose_name='请输入您的性别'),
        ),
    ]
